#!/usr/bin/env bash
###############################################################################
# MQTT‑Device‑Monitor unified installer / un‑installer                        #
#                                                                            #
#   Debian / Ubuntu   • macOS (Intel & Apple Silicon)                         #
#                                                                            #
# One‑liner (root inside LXC or sudo‑root):                                   #
#   curl -fsSL https://raw.githubusercontent.com/drascom/projects/main/mqtt-monitor/manage.sh | bash
#                                                                            #
# Re‑running the same line:                                                   #
#   • if NOT installed  → installs                                            #
#   • if installed     → completely removes                                   #
#                                                                            #
# Optional flags (manual override)                                            #
#   --install       Force install (over‑writes any existing copy)             #
#   --uninstall     Force uninstall only                                      #
#   --help          This help                                                 #
###############################################################################
set -Eeuo pipefail
shopt -s inherit_errexit

########## Constants ##########################################################
INSTALL_DIR="/opt/mqtt-device-monitor"     # single place for app files
REPO_URL="https://github.com/drascom/projects.git"
SYSTEMD_UNIT="/etc/systemd/system/mqtt-device-monitor.service"
LAUNCHD_PLIST="$HOME/Library/LaunchAgents/com.mqtt-device-monitor.plist"
PYTHON="python3"
OS=""      # linux|macos
DISTRO=""  # debian|ubuntu|arch|unknown
ACTUAL_USER=${SUDO_USER:-$(id -un)}

########## Pretty output ######################################################
RED="\033[0;31m"; GREEN="\033[0;32m"; YELLOW="\033[0;33m"; BLUE="\033[0;34m"; NC="\033[0m"
msg() { printf "%b%s%b\n" "${2:-$GREEN}" "$1" "$NC" >&2; }
require_root() { (( EUID==0 )) || { msg "❌  Must run as root" "$RED"; exit 1; }; }
run_as_user() { sudo -u "$ACTUAL_USER" "$@"; }
cmd_exists()  { command -v "$1" &>/dev/null; }

########## Detect OS ##########################################################
detect_os() {
  case $(uname -s) in
    Linux*)  OS="linux" ;;
    Darwin*) OS="macos" ;;
    *) msg "Unsupported OS $(uname -s)" "$RED"; exit 1 ;;
  esac
  if [[ $OS == linux ]]; then source /etc/os-release; DISTRO=${ID:-unknown}; fi
  msg "Detected $OS${DISTRO:+/$DISTRO}" "$BLUE"
}

########## Dependencies #######################################################
install_deps() {
  msg "Installing packages …" "$BLUE"
  if [[ $OS == linux ]]; then
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git curl build-essential mosquitto mosquitto-clients $PYTHON $PYTHON-venv
  else
    if ! cmd_exists brew; then
      msg "Installing Homebrew …" "$YELLOW"
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      eval "$(/opt/homebrew/bin/brew shellenv || /usr/local/bin/brew shellenv)"
    fi
    brew update
    brew install git mosquitto $PYTHON || true
    brew services start mosquitto || true
  fi
}

########## Mosquitto broker ###################################################
configure_mosquitto() {
  msg "Configuring Mosquitto …" "$BLUE"
  local conf passwd main_conf
  if [[ $OS == linux ]]; then
    conf="/etc/mosquitto/conf.d/mqtt-monitor.conf"
    passwd="/etc/mosquitto/passwd"
    main_conf="/etc/mosquitto/mosquitto.conf"
    mkdir -p /etc/mosquitto/conf.d
  else
    conf="$(brew --prefix)/etc/mosquitto/mqtt-monitor.conf"
    passwd="$(brew --prefix)/etc/mosquitto/passwd"
    main_conf="$(brew --prefix)/etc/mosquitto/mosquitto.conf"
  fi

  # interactive auth choice ---------------------------------------------------
  read -rp "MQTT username (blank = anonymous): " USERNAME </dev/tty || true
  if [[ -n $USERNAME ]]; then
    local pw1 pw2
    while true; do
      read -srp "Password for $USERNAME: " pw1 </dev/tty && echo
      read -srp "Confirm password: " pw2 </dev/tty && echo
      [[ $pw1 == $pw2 && -n $pw1 ]] && break
      msg "Passwords don't match – try again" "$YELLOW"
    done
    mosquitto_passwd -c -b "$passwd" "$USERNAME" "$pw1"
    chown mosquitto:mosquitto "$passwd"; chmod 600 "$passwd"
  fi

  # write dedicated conf snippet ---------------------------------------------
  cat >"$conf" <<EOF
# Generated by manage.sh – DO NOT EDIT BY HAND
listener 1883
protocol mqtt
listener 9001
protocol websockets
allow_anonymous $([[ -z $USERNAME ]] && echo true || echo false)
$( [[ -n $USERNAME ]] && echo "password_file $passwd" )
EOF

  # ensure main mosquitto.conf has no stale password_file ---------------------
  if [[ -z $USERNAME ]]; then
    sed -i '/^password_file[[:space:]]\+/d' "$main_conf" 2>/dev/null || true
  fi

  # restart -------------------------------------------------------------------
  if [[ $OS == linux ]]; then
    systemctl restart mosquitto; systemctl enable mosquitto
  else
    brew services restart mosquitto
  fi

  msg "Mosquitto ready (MQTT :1883  WS :9001)" "$GREEN"
}

########## Clone repo #########################################################
fetch_repo() {
  [[ -d $INSTALL_DIR ]] && { msg "Replacing old install" "$YELLOW"; rm -rf "$INSTALL_DIR"; }
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
  [[ -f $INSTALL_DIR/mqtt-monitor/main.py ]] || { msg "Repo layout unexpected" "$RED"; exit 1; }
}

########## Virtual env ########################################################
setup_venv() {
  cd "$INSTALL_DIR/mqtt-monitor"
  $PYTHON -m venv .venv
  . .venv/bin/activate
  pip install --upgrade pip
  [[ -f requirements.txt ]] && pip install -r requirements.txt
  deactivate
}

########## .env wizard ########################################################
create_env_file() {
  cd "$INSTALL_DIR/mqtt-monitor"
  local env=.env broker="localhost" port=9001 gui_port=9876 id="$(hostname)"
  read -rp "Broker hostname [$broker]: " tmp </dev/tty || true; broker=${tmp:-$broker}
  read -rp "Broker port [$port]: " tmp </dev/tty || true; port=${tmp:-$port}
  read -rp "GUI port [$gui_port]: " tmp </dev/tty || true; gui_port=${tmp:-$gui_port}
  cat >"$env" <<EOF
MQTT_BROKER=$broker
MQTT_PORT=$port
MQTT_USERNAME=$USERNAME
MQTT_PASSWORD=$pw1
DEVICE_ID=$id
GUI_HOST=0.0.0.0
GUI_PORT=$gui_port
EOF
  chmod 600 "$env"
}

########## Service files ######################################################
create_service() {
  if [[ $OS == linux ]]; then
    cat >"$SYSTEMD_UNIT" <<EOF
[Unit]
Description=MQTT Device Monitor
After=network.target mosquitto.service
[Service]
Type=simple
User=$ACTUAL_USER
WorkingDirectory=$INSTALL_DIR/mqtt-monitor
ExecStart=$INSTALL_DIR/mqtt-monitor/.venv/bin/python main.py
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now mqtt-device-monitor.service
  else
    cat >"$LAUNCHD_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.mqtt-device-monitor</string>
  <key>ProgramArguments</key><array>
    <string>$INSTALL_DIR/mqtt-monitor/.venv/bin/python</string>
    <string>$INSTALL_DIR/mqtt-monitor/main.py</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>WorkingDirectory</key><string>$INSTALL_DIR/mqtt-monitor</string>
</dict></plist>
EOF
    chown "$ACTUAL_USER" "$LAUNCHD_PLIST"
    launchctl unload "$LAUNCHD_PLIST" 2>/dev/null || true
    launchctl load "$LAUNCHD_PLIST"
  fi
}

########## Clean removal ######################################################
remove_all() {
  msg "Uninstalling …" "$BLUE"
  [[ -f $SYSTEMD_UNIT ]] && { systemctl disable --now mqtt-device-monitor.service || true; rm -f "$SYSTEMD_UNIT"; systemctl daemon-reload; }
  [[ -f $LAUNCHD_PLIST ]] && { launchctl unload "$LAUNCHD_PLIST" || true; rm -f "$LAUNCHD_PLIST"; }
  rm -rf "$INSTALL_DIR"
  msg "Removal complete" "$GREEN"
}

########## CLI parsing ########################################################
OP=auto
case "${1:-}" in
  --install)   OP=install ;;
  --uninstall) OP=uninstall ;;
  -h|--help)   grep -m1 -A99 "^###############################################################################" "$0" | sed '1,2d;/^###############################################################################/q'; exit 0 ;;
esac
require_root
detect_os

# decide auto behaviour
[[ $OP == auto ]] && [[ -d $INSTALL_DIR ]] && OP=uninstall || [[ $OP == auto ]] && OP=install

if [[ $OP == uninstall ]]; then remove_all; exit 0; fi

install_deps
configure_mosquitto
fetch_repo
setup_venv
create_env_file
create_service
msg "✅  Done. GUI -> http://$(hostname -I 2>/dev/null | awk '{print $1}'):${gui_port:-9876}" "$GREEN"
